dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip install tox
  
# command to run tests
script:
  - tox
  
# Push the results back to codecov
after_success:
- bash <(curl -s https://codecov.io/bash)
